# refer to http://www.yaml.org/spec/1.1/ for clarification on YAML collections
barcamp:
  path: ../../blueprint/
  custom_layout:
    column_count: 12
    column_width: 60
    gutter_width: 10
  plugins:
    - fancy-type
    - buttons
